# Mathematical & Statistical Operations in NumPy

In [2]:
import numpy as np

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

np.add(a1, a2)

array([5, 7, 9])

In [3]:
np.subtract(a1, a2)

array([-3, -3, -3])

In [4]:
np.multiply(a1, a2)

array([ 4, 10, 18])

In [5]:
np.divide(a1, a2)

array([0.25, 0.4 , 0.5 ])

In [7]:
np.divmod(a2, a1)

(array([4, 2, 2]), array([0, 1, 0]))

In [8]:
np.sum(np.arange(10))

np.int64(45)

In [ ]:
a1 = np.random.randint(1, 100) # random values
a1

57

In [4]:
np.random.seed(1) # fixed value for random values
# np.random.random((2, 5))
a1 = np.random.random(10)
a1

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [ ]:
1e3 # 1e = 10, power=3, for decimal power in minus 

1000.0

In [23]:
# np.random.uniform(10)
np.mean(a1)

np.float64(0.4652883857420364)

In [25]:
np.mean(np.random.random((2, 5)))

np.float64(0.41993218627918366)

In [ ]:
a1 = np.random.random_integers(1, 100, 50)

C:\Users\acer\AppData\Local\Temp\ipykernel_2812\2216515129.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a1 = np.random.random_integers(1, 100, 50)


array([14, 10,  8, 64, 62, 23, 58,  2,  1, 61, 82,  9, 89, 14, 48, 73, 31,
       72,  4, 71, 22, 50, 58,  4, 69, 25, 44, 77, 27, 53, 81, 42, 83, 16,
       65, 69, 26, 99, 88,  8, 27, 26, 23, 10, 68, 24, 28, 38, 58, 84],
      dtype=int32)

In [28]:
np.max(a1), np.min(a1)

(np.int32(99), np.int32(1))

In [30]:
np.argmax(a1), np.argmin(a1)

(np.int64(37), np.int64(8))

In [8]:
a1 = np.random.random_integers(1, 100, (5, 5))
a1

C:\Users\acer\AppData\Local\Temp\ipykernel_16168\2592620425.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a1 = np.random.random_integers(1, 100, (5, 5))


array([[19, 85, 12, 29, 30],
       [15, 51, 69, 88, 88],
       [95, 97, 87, 14, 10],
       [ 8, 64, 62, 23, 58],
       [ 2,  1, 61, 82,  9]], dtype=int32)

In [33]:
np.max(a1), np.min(a1)


(np.int32(97), np.int32(3))

In [ ]:
np.argmax(a1), np.argmin(a1)
#1 d

(np.int64(21), np.int64(2))

In [ ]:
# np.unravel_index(9, a1.shape)
np.unravel_index(np.argmax(a1), a1.shape)


(np.int64(4), np.int64(1))

In [40]:
np.unravel_index(np.argmin(a1), a1.shape)


(np.int64(0), np.int64(2))

In [9]:
np.sqrt(a1)

array([[4.35889894, 9.21954446, 3.46410162, 5.38516481, 5.47722558],
       [3.87298335, 7.14142843, 8.30662386, 9.38083152, 9.38083152],
       [9.74679434, 9.8488578 , 9.32737905, 3.74165739, 3.16227766],
       [2.82842712, 8.        , 7.87400787, 4.79583152, 7.61577311],
       [1.41421356, 1.        , 7.81024968, 9.05538514, 3.        ]])

In [10]:
np.cbrt(a1)

array([[2.66840165, 4.39682967, 2.28942849, 3.07231683, 3.10723251],
       [2.46621207, 3.70842977, 4.10156593, 4.44796018, 4.44796018],
       [4.56290264, 4.59470089, 4.43104762, 2.41014226, 2.15443469],
       [2.        , 4.        , 3.95789161, 2.84386698, 3.87087664],
       [1.25992105, 1.        , 3.93649718, 4.34448149, 2.08008382]])

In [11]:
np.log(a1)

array([[2.94443898, 4.44265126, 2.48490665, 3.36729583, 3.40119738],
       [2.7080502 , 3.93182563, 4.2341065 , 4.47733681, 4.47733681],
       [4.55387689, 4.57471098, 4.46590812, 2.63905733, 2.30258509],
       [2.07944154, 4.15888308, 4.12713439, 3.13549422, 4.06044301],
       [0.69314718, 0.        , 4.11087386, 4.40671925, 2.19722458]])

In [12]:
np.log10(a1)

array([[1.2787536 , 1.92941893, 1.07918125, 1.462398  , 1.47712125],
       [1.17609126, 1.70757018, 1.83884909, 1.94448267, 1.94448267],
       [1.97772361, 1.98677173, 1.93951925, 1.14612804, 1.        ],
       [0.90308999, 1.80617997, 1.79239169, 1.36172784, 1.76342799],
       [0.30103   , 0.        , 1.78532984, 1.91381385, 0.95424251]])

In [13]:
np.log2(a1)


array([[4.24792751, 6.40939094, 3.5849625 , 4.857981  , 4.9068906 ],
       [3.9068906 , 5.67242534, 6.10852446, 6.45943162, 6.45943162],
       [6.56985561, 6.59991284, 6.4429435 , 3.80735492, 3.32192809],
       [3.        , 6.        , 5.95419631, 4.52356196, 5.857981  ],
       [1.        , 0.        , 5.93073734, 6.357552  , 3.169925  ]])

- [Mathematical function]( https://numpy.org/doc/2.2/reference/routines.math.html)
- [Statistical functions](https://numpy.org/doc/2.2/reference/routines.statistics.html)