# Linear algebra with NumPy

In [1]:
import numpy as np

In [ ]:
np.eye(5, 5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3, 4) # in identity genrally in square matrix if not truncates

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [4]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [5]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.diagonal(arr)

array([0, 4, 8])

In [7]:
[
    [1, 2],
    [3, 4]
]
# Determinant = 1*4 - 2*3 = -2

[[1, 2], [3, 4]]

In [8]:
arr = np.arange(1, 5).reshape((2, 2))
arr

array([[1, 2],
       [3, 4]])

In [ ]:
np.linalg.det(arr) # to calculate determinant

np.float64(-2.0000000000000004)

In [ ]:
# to calculate inverse, should always be square matrix
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.det(arr) # singular matric so inverse cannot be calculated

np.float64(0.0)

In [13]:
arr = np.random.random_integers(0, 10, (3, 3))

C:\Users\acer\AppData\Local\Temp\ipykernel_15764\507228154.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  arr = np.random.random_integers(0, 10, (3, 3))


In [14]:
np.linalg.inv(arr)

array([[-0.08602151,  0.17204301, -0.01075269],
       [-0.19354839, -0.11290323,  0.22580645],
       [ 0.22580645,  0.0483871 , -0.09677419]])

In [ ]:
[[1, 2] 
 [3, 4]]

#---
[[1, 3],
 [2, 4]]

### Transpose 
- Converts rows into columns and cice versa of matrix (for 2d)

In [15]:
arr = np.arange(1, 5).reshape((2, 2))
arr

array([[1, 2],
       [3, 4]])

In [16]:
arr.T

array([[1, 3],
       [2, 4]])

In [17]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [ ]:
# eigen values and eigen vectors
A * e_vector = e_values * e_vector

In [20]:
e_val, e_vec = np.linalg.eig(arr)
e_val, e_vec

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
# 2x + 3y = 10
# x - y = 2

In [22]:
coeff = np.array([
    [2, 3],
    [1, -1]
])

y = np.array([10, 2])

np.linalg.solve(coeff, y)

array([3.2, 1.2])

In [23]:
2*3.2 + 3*1.2

10.0

In [24]:
# x + y -2z = 7
# -2x + 3y -4z = 5
# 4x - 5y + 6z = 11

coeff = np.array([
    [1, 1, -2],
    [-2, 3, -4],
    [4, -5, 6]
])

y = np.array([7, 5, 11])

np.linalg.solve(coeff, y)

array([-14., -65., -43.])

In [ ]:
# matrix multiplication
# a, b => arrays
# np.dot
# a @ b

In [26]:
a, b = np.arange(4).reshape((2, 2)), np.arange(2, 6).reshape((2, 2))
print(np.dot(a, b))
print("-" * 10)
print( a @ b)

[[ 4  5]
 [16 21]]
----------
[[ 4  5]
 [16 21]]
