# Pandas Introduction (Series and Dataframes)

In [ ]:
# Install python packages from notebook cell
# ! pip install pandas

In [4]:
# %%timeit
import numpy as np
# np.arange(900).reshape((9, 100))

In [3]:
import pandas as pd

# Series

In [8]:
l = [1, 2, 3, 4, 5, 6]
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [12]:
s1 = pd.Series(l)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
pd.Series(arr)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [9]:
index = list('abcde')
index

['a', 'b', 'c', 'd', 'e']

In [19]:
s2=pd.Series(arr, index = index, name = 'demo') # index values can be changed from
s2

a    0
b    1
c    2
d    3
e    4
Name: demo, dtype: int64

In [14]:
s1[0], s1.loc[0]

(np.int64(1), np.int64(1))

In [20]:
s2[0], s2.loc['a'], s2.iloc[0]

C:\Users\acer\AppData\Local\Temp\ipykernel_9724\3089942900.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[0], s2.loc['a'], s2.iloc[0]


(np.int64(0), np.int64(0), np.int64(0))

In [23]:
arr = np.arange(12).reshape((3, 2, 2))
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [28]:
tp = np.transpose(arr, (1, 0, 2))
tp

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

In [29]:
tp.shape

(2, 3, 2)

In [ ]:
tp = np.transpose(arr, (1, 2, 0)) # to change dimension or axis
tp

array([[[ 0,  4,  8],
        [ 1,  5,  9]],

       [[ 2,  6, 10],
        [ 3,  7, 11]]])