# Array Indexing, Slicing and Reshaping

### Indexing

In [2]:
import numpy as np

In [6]:
# In 1 D array
arr1d = np.arange(18).astype(np.str_)
arr1d

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17'], dtype='<U21')

In [7]:
arr1d[13]

np.str_('13')

In [9]:
#2d indexing
l = [
    [1, 2, 3], 
    [4, 5, 6]
]

l[1][1]

5

In [21]:
arr2d = np.array(l)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2d[1][1], arr2d[1, 1]

(np.int64(5), np.int64(5))

In [20]:
# 3d 
l3 = [
    [[1, 2 ,3, 4],
    [5, 6, 7, 8]],
    [[9, 10, 11, 12],
     [13, 14, 15, 16]]
]

l3[0][1][0]

5

In [23]:
arr3d = np.array(l3)
arr3d[0, 1, 0]

np.int64(5)

In [31]:
arr3d_2 = np.arange(18).reshape((3, 6, 1))
arr3d_2
arr3d_2[1, 4, 0]

np.int64(10)

### Slicing

In [32]:
# 1d
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr[1:5:2]

array([1, 3])

In [36]:
#2d
arr = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]
)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr[1:3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
arr[1:3:, :2:]

array([[4, 5],
       [7, 8]])

In [44]:
arr = np.arange(36).reshape(6, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [53]:
arr[4::, 4::]

array([[28, 29],
       [34, 35]])

In [54]:
arr[::2]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [59]:
arr[::2, 1::2]


array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [61]:
arr = np.arange(36).reshape(3, 2, 6)
arr

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [67]:
# arr[::, ::, ::]
arr[:2:, 1::, 1:5:]

array([[[ 7,  8,  9, 10]],

       [[19, 20, 21, 22]]])

# Reshaping

In [68]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
arr.shape

(12,)

In [ ]:
arr.reshape((3, 2, 2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [72]:
arr.reshape((3, 4, 1))


array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [74]:
arr4d = arr.reshape((3, 2, 2, 1))
arr4d

array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]]],


       [[[ 4],
         [ 5]],

        [[ 6],
         [ 7]]],


       [[[ 8],
         [ 9]],

        [[10],
         [11]]]])

In [75]:
arr4d.reshape((2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# -1 puts the desired value
arr.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
arr.reshape((2, -1, 2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [87]:
arr.reshape(( -1, 1))


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])