# Numpy

In [1]:
import numpy as np

In [3]:
l =[1, 2, 3, 4]

In [5]:
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [6]:
type(l), type(arr)
#type ndarray no matter the dimension

(list, numpy.ndarray)

In [7]:
#creating array from tuple
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [8]:
arr.dtype

dtype('int64')

In [9]:
#ndim = for number of dimension
arr.ndim

1

given matrix <br> 
|1 2 3| <br>
|4 5 6|<br>
|7 8 9|

In [20]:
matrix_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrix_list
#list representation

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
arr2 = np.array(matrix_list)
arr2
# array representation

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(3, 3)

In [24]:
arr2.argmax()

np.int64(8)

In [25]:
# provides result in one dimension no matter how many dimensions
arr2.argmin()

np.int64(0)

In [26]:
arr.dtype

dtype('int64')

In [32]:
# convert to another datatype
arr2.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [33]:
list(range(0, 5, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [37]:
np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(0, 5, 0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [39]:
np.linspace(0, 10, 5)
# close bound, start and ending both, equally spaced numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
np.linspace(0, 10, 20)


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Python's `all()` and `any()`

In [44]:
# all and any return boolean
# if no elements = false, if 1 or many then true
if {'a' : 2}:
    print("inside if statement")
else: 
    print("inside else statement")

inside if statement


In [45]:
l = [True, [], 4]

In [47]:
all(l), any(l)

(False, True)

In [50]:
# if string has even space then true return
if -1:
    print("inside if statement")
else: 
    print("inside else statement")

inside if statement


In [52]:
np.all(arr2), np.any(arr2)

(np.True_, np.True_)

In [53]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.zeros((2, 3), dtype = np.int32)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [59]:
np.ones((3, 4, 5), dtype=np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [61]:
arr3 = np.arange(12)
arr3, arr3.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [78]:
#
arr_r1 = arr3.reshape((3, 2, 2))
# arr_r1 = arr3.reshape((2, 6))
arr_r1, arr_r1.shape, arr_r1.ndim


(array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11]]]),
 (3, 2, 2),
 3)

In [67]:
arr_r1 = arr3.reshape((2, 6))
arr_r1, arr_r1.shape, arr_r1.ndim

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6),
 2)

In [81]:
#access 1st dimension ko 1st element
arr_r1[2][1][1]

np.int64(11)

In [ ]:
#0 dimension array = scalar = no numbers