# Broadcasting and vectorization

In [1]:
2 + 3

5

In [2]:
a, b = [1, 2], [3, 4]
total = []
for i in range(2):
    total.append(a[i] + b[i])

print(total)

[4, 6]


In [3]:
[i + j for i, j in zip(a, b)]

[4, 6]

In [1]:
[1, 1], [1, 2]

([1, 1], [1, 2])

In [ ]:
# broadcast: project lower dimensional array to higher dimensional array

### Broadcasting

In [2]:
import numpy as np

In [4]:
arr1= np.arange(9).reshape((3, 3))
arr2= np.arange(3)
print(arr1)
print()
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2]


In [7]:
# should match the dimension of array to do any operations
#if arr2 has np.arange(4), it will show valueError
arr2 + arr1

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [11]:
arr1 = np.arange(9).reshape((3, 3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr1 + 100 # scalar addition, adds to every element by 100

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

In [13]:
arr1 * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr1 / 3

array([[0.        , 0.33333333, 0.66666667],
       [1.        , 1.33333333, 1.66666667],
       [2.        , 2.33333333, 2.66666667]])

In [16]:
a1 = np.arange(9).reshape((3, 3))
a2 = np.arange(9, 18).reshape((3, 3))
a1, a2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]))

In [17]:
a1 + a2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [18]:
a1 = np.arange(4)
a2 = np.arange(4, 8)
a1, a2

(array([0, 1, 2, 3]), array([4, 5, 6, 7]))

In [ ]:
# vector dot product is always a scalar value
np.dot(a1, a2) # 0*4 + 1*5 + 2*6 + 3*7 = 38

np.int64(38)

In [21]:
a1 = np.arange(9).reshape((3, 3))
a2 = np.arange(9, 27, 2).reshape((3, 3))
a1, a2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]]))

In [ ]:
np.dot(a1, a2) # 0*9 + 1*15 + 2*21 = 57, 0*11 + 1*17 + 2*23 = 63, 3*9 + 4*15 + 5*21= 192 .....n

array([[ 57,  63,  69],
       [192, 216, 240],
       [327, 369, 411]])

In [24]:
a1 = np.arange(8).reshape((2, 2, 2))
a2 = np.arange(1, 3)
print(a1, a2)
print(a1.shape, a2.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] [1 2]
(2, 2, 2) (2,)


In [ ]:
np.dot(a1, a2) # 0*1 + 1*2 = 2, 2*1 + 3*2 = 6 | 4*1 + 5*2 = 14, 6*1 + 7*2 = 20 -> [2 X 2]

array([[ 2,  8],
       [14, 20]])

In [31]:
a1 = np.arange(18).reshape((3, 3, 2))
a2 = np.arange(8).reshape((2, 4))
print(a1, '\n\n', a2)
print(a1.shape, a2.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]] 

 [[0 1 2 3]
 [4 5 6 7]]
(3, 3, 2) (2, 4)


In [ ]:
result = np.dot(a1, a2) 
result
# result.shape = (3, 3, 4)


array([[[  4,   5,   6,   7],
        [ 12,  17,  22,  27],
        [ 20,  29,  38,  47]],

       [[ 28,  41,  54,  67],
        [ 36,  53,  70,  87],
        [ 44,  65,  86, 107]],

       [[ 52,  77, 102, 127],
        [ 60,  89, 118, 147],
        [ 68, 101, 134, 167]]])

In [ ]:
# def cube (x: list):
#     return [ele**3 for ele in x]
# cube([1, 2, 3])

def cube (x: int):
    return x**3

for ele in range(1, 4):
    print(cube(ele))

1
8
27


In [40]:
cube_vec = np.vectorize(cube)
cube_vec([1, 2, 3])

array([ 1,  8, 27])