In [1]:
import numpy as np

In [3]:
# nan - not a number 
# inf = infinity
np.nan, np.inf

(nan, inf)

In [4]:
a1 = np.array(([1, 2, 3, np.nan, 5, 6]))
a1

array([ 1.,  2.,  3., nan,  5.,  6.])

In [5]:
np.isnan(a1)

array([False, False, False,  True, False, False])

In [6]:
a2 = np.array(([1, 2, 3, np.inf, 5, 6]))
a2


array([ 1.,  2.,  3., inf,  5.,  6.])

In [7]:
np.isfinite(a2)

array([ True,  True,  True, False,  True,  True])

In [8]:
a3 = np.array([1, np.nan, 3, np.inf, 5])
a3

array([ 1., nan,  3., inf,  5.])

In [21]:
mask_arr = np.array([True, False, True, False, True])
mask_arr

array([ True, False,  True, False,  True])

In [20]:
a3[[True, False, True, False, True]], a3[mask_arr]

(array([1., 3., 5.]), array([1., 3., 5.]))

In [18]:
np.isfinite(a3)

array([ True, False,  True, False,  True])

In [17]:
a3[np.isfinite(a3)]

array([1., 3., 5.])

In [22]:
~np.isfinite(a3)

array([False,  True, False,  True, False])

In [ ]:
a3[~np.isfinite(a3)]

array([nan, inf])

In [24]:
a4 = np.array([1, 2, np.nan, 4])
a4


array([ 1.,  2., nan,  4.])

In [25]:
np.isnan(a4)

array([False, False,  True, False])

In [ ]:
# replace nan value
a4[np.isnan(a4)] = 1000
a4

array([   1.,    2., 1000.,    4.])

In [28]:
a3[np.isnan(a3)] = 1000
a3

array([   1., 1000.,    3.,   inf,    5.])

In [29]:
a3 = np.array([1, np.nan, 3, np.inf, 5])
a3

array([ 1., nan,  3., inf,  5.])

In [ ]:
# replace non-finite value to 100 (~np.isfinite(a))
a3[~np.isfinite(a3)] = 100
a3

array([  1., 100.,   3., 100.,   5.])

In [59]:
a5 = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])
a5

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [34]:
a5[np.isnan(a5)]

array([nan, nan])

In [ ]:
np.where(np.isnan(a5)) # 1st row has nan value = 0, 2nd row has nan value, 2nd index has nan value = 2, 1st index has nan value = 1 

(array([0, 1]), array([2, 1]))

In [50]:
np.where(np.isnan(a5))[1]

array([2, 1])

- first nan value has index (0, 2)
- second nan value has index (1, 1)

In [36]:
a5

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [37]:
np.mean(a5)

np.float64(nan)

In [ ]:
np.nanmean(a5)

np.float64(5.285714285714286)

- axis = 0 : column-wise operation
- axis = 1 : row-wise operation

In [ ]:
# col==> 1+4+7 = 12, 12/3 = 4 || row ==> 1+2+nan = 3/2 = 1.5
col_mean, row_mean = np.nanmean(a5, axis=0), np.nanmean(a5, axis=1)
col_mean, row_mean


(array([4. , 5. , 7.5]), array([1.5, 5. , 8. ]))

In [ ]:
# nan value index's value
np.take(col_mean, np.where(np.isnan(a5))[1])

array([7.5, 5. ])

In [58]:
a5

array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [55]:
a5[np.isnan(a5)] = np.take(col_mean, np.where(np.isnan(a5))[1])
a5

array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [ ]:
a5[np.isnan(a5)] = np.take(row_mean, np.where(np.isnan(a5))[0])
# np.array([nan, nan]) = np.array([1.5, 5])
a5

array([[1. , 2. , 1.5],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

array([], dtype=float64)