In [47]:
import tensorflow as tf
import numpy as np

In [48]:
tf.__version__

'2.19.0'

### Tensorflow

In [49]:
import numpy as np

l = [1, 2 ,3]
arr = np.array(1)
arr, type(arr)


(array(1), numpy.ndarray)

In [50]:
tensor1 = tf.constant(l)
tensor1, type(tensor1)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [51]:
tensor2 = tf.constant(arr)
tensor2, type(tensor2)

l2 = [
    [1, 2],
    [3, 4]
]
tensor3 = tf.constant(l2)
tensor3, type(tensor3)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [52]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
tf.zeros((2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [54]:
tf.ones((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [55]:
# tf.eye((3, 2))

In [56]:
tf.eye(num_rows = 2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [57]:
tf.eye(num_rows=3, num_columns=2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

In [58]:
np.random.random((3, 3))

array([[0.15580836, 0.59131054, 0.04986238],
       [0.76452289, 0.26440421, 0.0109091 ],
       [0.3088673 , 0.36091112, 0.22169047]])

In [59]:
tf.random.normal((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.77785426,  0.05420981,  0.39813444],
       [ 0.9383775 , -1.022192  ,  1.1249107 ],
       [-0.2688913 ,  0.28926995, -2.2253418 ]], dtype=float32)>

### Reshaping and Slicing 

In [60]:
tensor = tf.random.normal((4, 3))
tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.82234937, -0.798912  , -0.6245051 ],
       [-1.9242176 ,  0.06628928,  1.0831932 ],
       [ 1.6952769 , -1.6494827 ,  1.0864013 ],
       [ 0.8897388 ,  0.8971018 ,  0.3066175 ]], dtype=float32)>

In [61]:
tf.reshape(tensor, (2, 6))

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[-0.82234937, -0.798912  , -0.6245051 , -1.9242176 ,  0.06628928,
         1.0831932 ],
       [ 1.6952769 , -1.6494827 ,  1.0864013 ,  0.8897388 ,  0.8971018 ,
         0.3066175 ]], dtype=float32)>

In [62]:
tf.reshape(tensor, (2, 2, 3))

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.82234937, -0.798912  , -0.6245051 ],
        [-1.9242176 ,  0.06628928,  1.0831932 ]],

       [[ 1.6952769 , -1.6494827 ,  1.0864013 ],
        [ 0.8897388 ,  0.8971018 ,  0.3066175 ]]], dtype=float32)>

In [63]:
t5d = tf.reshape(tensor, (1, 2, 2, 1, 3))
t5d

<tf.Tensor: shape=(1, 2, 2, 1, 3), dtype=float32, numpy=
array([[[[[-0.82234937, -0.798912  , -0.6245051 ]],

         [[-1.9242176 ,  0.06628928,  1.0831932 ]]],


        [[[ 1.6952769 , -1.6494827 ,  1.0864013 ]],

         [[ 0.8897388 ,  0.8971018 ,  0.3066175 ]]]]], dtype=float32)>

In [64]:
tf.squeeze(t5d)
# removes one dimension

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.82234937, -0.798912  , -0.6245051 ],
        [-1.9242176 ,  0.06628928,  1.0831932 ]],

       [[ 1.6952769 , -1.6494827 ,  1.0864013 ],
        [ 0.8897388 ,  0.8971018 ,  0.3066175 ]]], dtype=float32)>

In [65]:
t1d = tf.reshape(tensor, (12,))
t1d

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([-0.82234937, -0.798912  , -0.6245051 , -1.9242176 ,  0.06628928,
        1.0831932 ,  1.6952769 , -1.6494827 ,  1.0864013 ,  0.8897388 ,
        0.8971018 ,  0.3066175 ], dtype=float32)>

In [66]:
t2d = tf.reshape(tensor, (1, 12))
t2d

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[-0.82234937, -0.798912  , -0.6245051 , -1.9242176 ,  0.06628928,
         1.0831932 ,  1.6952769 , -1.6494827 ,  1.0864013 ,  0.8897388 ,
         0.8971018 ,  0.3066175 ]], dtype=float32)>

In [67]:
tf.squeeze(t2d)

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([-0.82234937, -0.798912  , -0.6245051 , -1.9242176 ,  0.06628928,
        1.0831932 ,  1.6952769 , -1.6494827 ,  1.0864013 ,  0.8897388 ,
        0.8971018 ,  0.3066175 ], dtype=float32)>

In [68]:
tf.squeeze(t5d, axis = 3)

<tf.Tensor: shape=(1, 2, 2, 3), dtype=float32, numpy=
array([[[[-0.82234937, -0.798912  , -0.6245051 ],
         [-1.9242176 ,  0.06628928,  1.0831932 ]],

        [[ 1.6952769 , -1.6494827 ,  1.0864013 ],
         [ 0.8897388 ,  0.8971018 ,  0.3066175 ]]]], dtype=float32)>

In [69]:
tf.squeeze(t5d, axis=[0, 3])

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.82234937, -0.798912  , -0.6245051 ],
        [-1.9242176 ,  0.06628928,  1.0831932 ]],

       [[ 1.6952769 , -1.6494827 ,  1.0864013 ],
        [ 0.8897388 ,  0.8971018 ,  0.3066175 ]]], dtype=float32)>

In [70]:
tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.82234937, -0.798912  , -0.6245051 ],
       [-1.9242176 ,  0.06628928,  1.0831932 ],
       [ 1.6952769 , -1.6494827 ,  1.0864013 ],
       [ 0.8897388 ,  0.8971018 ,  0.3066175 ]], dtype=float32)>

In [71]:
tf.expand_dims(tensor, axis=0)

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[-0.82234937, -0.798912  , -0.6245051 ],
        [-1.9242176 ,  0.06628928,  1.0831932 ],
        [ 1.6952769 , -1.6494827 ,  1.0864013 ],
        [ 0.8897388 ,  0.8971018 ,  0.3066175 ]]], dtype=float32)>

In [72]:
tf.expand_dims(tensor, axis=-1)

<tf.Tensor: shape=(4, 3, 1), dtype=float32, numpy=
array([[[-0.82234937],
        [-0.798912  ],
        [-0.6245051 ]],

       [[-1.9242176 ],
        [ 0.06628928],
        [ 1.0831932 ]],

       [[ 1.6952769 ],
        [-1.6494827 ],
        [ 1.0864013 ]],

       [[ 0.8897388 ],
        [ 0.8971018 ],
        [ 0.3066175 ]]], dtype=float32)>

In [73]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [74]:
np.array([[1, 2], [3, 4]]).T


array([[1, 3],
       [2, 4]])

In [75]:
tensor2 = tf.constant([[1, 2], [3, 4]])
tf.transpose(tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [76]:
tensor3 = tf.constant([[[1], [2]], [[3], [4]], [[5], [6]]])
# tf.transpose(tensor3)
tensor3.shape(), tf,tensor(tensor3)


TypeError: 'TensorShape' object is not callable

In [ ]:
tf.transpose(tensor3, perm=[0, 1, 2])


In [ ]:
tf.transpose(tensor3, perm=[1, 2, 0])


In [ ]:
tensor3

In [ ]:
tensor3[1]

In [ ]:
tensor3[1, 1, 0]

In [ ]:
tensor3[1:, 1:]

In [ ]:
t1 = tf.constant([1, 2])
t2 = tf.constant([10, 20])
tf.add(t1, t2)

In [ ]:
t1 + t2

In [ ]:
t2 - t1

In [ ]:
tf.multiply(t1, t2)

In [ ]:
tf.divide(t2, t1)

In [ ]:
tf.math.pow(t1, 2)

In [ ]:
t1 = tf.constant([1.0, 2.0])
tf.math.exp(t1)

In [ ]:
tf.math.log(t1)

### Activation function

In [ ]:
t3 = tf.constant([0, 1, 2, 4, -4, -2, 11, -14], dtype=tf.float32)
t3

In [ ]:
tf.nn.relu(t3)
#if positive value then constant, if negative then turns to 0

In [ ]:
tf.nn.softmax(t3)

In [ ]:
t3

In [ ]:
tf.reduce_sum(t3)

In [ ]:
tf.reduce_mean(t3)

In [ ]:
tf.reduce_max(t3)

In [ ]:
tf.reduce_min(t3)

In [ ]:
tf.reduce_prod(t3)

In [ ]:
tf.argmax(t3)

In [ ]:
tf.argmin(t3)

In [ ]:
# t4 = tf.constant([[2, 3], [5, 6]])
t4 = tf.constant([[2, 3], [15, 6]])
tf.argmax(t4, axis=1)

### Linear Algebra

In [ ]:
t4 = tf.constant([[2, 3], [15, 6]])
t5 = tf.constant([[2, 1], [1, 6]])
tf.linalg.matmul(t4, t5)

In [ ]:
t4 = tf.constant([[2, 3], [15, 6]], dtype=tf.float32)
tf.linalg.inv(t4)

In [ ]:
tf.linalg.det(t4)

## Comparision and Boolean

In [ ]:
t6 = tf.constant([1])
t7 = tf.constant([1])

tf.equal(t6, t7)

In [ ]:
t6 = tf.constant([1])
t7 = tf.constant([1], dtype=tf.float32)

tf.equal(t6, t7)
# have same datatype

In [ ]:
# !=

tf.not_equal(t6, t7)

In [ ]:
tf.less(t6, t7)

In [ ]:
tf.greater_equal(t6, t7)

In [ ]:
tf.less_equal(t6, t7)

In [ ]:
tf.where(t4 > 2, t4, 0)

## Type casting

In [ ]:
a = 1

In [ ]:
a = float(a)
a

In [ ]:
t8 = tf.constant([1])
t8

In [ ]:
tf.cast(t8, dtype=tf.float32)