### Topic 1 : Creating Arrays
Task 1: Write a Python program to create a NumPy array of integers from 1 to
20 and reshape it into a 4×5 matrix.

In [4]:
import numpy as np

In [5]:
arr = np.arange(1, 21).reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Task 2. Create a NumPy array of shape (5,5) filled with random float values
between 0 and 1.

In [6]:
arr2 = np.random.rand(5, 5)
arr2

array([[0.9349993 , 0.88274222, 0.14855563, 0.09256174, 0.91415216],
       [0.19618211, 0.4914719 , 0.6350959 , 0.34241517, 0.18463478],
       [0.45594105, 0.55795149, 0.69815797, 0.2843988 , 0.61210347],
       [0.54938367, 0.91926847, 0.19040744, 0.27865476, 0.80583917],
       [0.62979906, 0.8881811 , 0.15899139, 0.87106456, 0.83958498]])

Task 3. Write a function that takes a list as input and converts it into a NumPy
array. Ensure the function can handle lists of different lengths and nested lists.

In [7]:
def convert_list(list_input):
    list_arr = np.array(list_input, dtype=list)
    return list_arr

user_input = input("Enter a list of numbers:")
user_input = user_input.replace("][", "], [")
user_list = eval(user_input)
convert_list(user_list)

array([1, 2, 3, 4], dtype=object)

Task 4. Create an identity matrix of size 6×6 using NumPy.

In [80]:
identity_matrix = np.eye(6, 6)
identity_matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Task 5. Generate an array of 10 evenly spaced values between -5 and 5 using
`linspace`. Explain the difference between `linspace` and `arange`.


In [ ]:
even_spaced_arr = np.linspace(0, 5, 10)
even_spaced_arr
# linspace is used to evenly divide the range from start to stop into a specific number of values, 
# while arange is used when you want numbers with a specific step between them.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Task 6. Create a 3D NumPy array of shape (3,3,3) filled with random integers
between 10 and 50.

In [23]:
random_arr3 = np.random.random_integers(10, 50, (3, 3, 3))
random_arr3

C:\Users\acer\AppData\Local\Temp\ipykernel_16032\1200005687.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 50 + 1) instead
  random_arr3 = np.random.random_integers(10, 50, (3, 3, 3))


array([[[33, 41, 27],
        [31, 11, 38],
        [42, 28, 33]],

       [[30, 38, 28],
        [35, 33, 19],
        [29, 18, 30]],

       [[44, 48, 38],
        [15, 19, 24],
        [48, 42, 18]]], dtype=int32)


Task 7. Write a Python program to generate an array of zeros and ones of shape
(4,4).

In [94]:
zeros_arr = np.zeros((4, 4), dtype = np.int32)
ones_arr = np.ones((4, 4), dtype = np.int32)
zeros_arr, ones_arr

(array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=int32),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=int32))

Task 8. Generate a NumPy array of 100 random integers between 1 and 1000.
Find the maximum, minimum, and mean values in the array.


In [38]:
arr4 = np.random.randint(1, 1000, 100)
max_val = np.max(arr4)
min_val = np.min(arr4)
mean_val = np.mean(arr4)

print(f'Array Values: {arr4}')
print(f'Max value: {max_val}',
    f'Min value: {min_val}',
    f'Mean value: {mean_val}')

Array Values: [550  51 115 764 807 474 517 435 106 773 840 782 177 845 992 835 719 594
 488 251 169 418 958 349 982 350 457 921 456 930 616 153  74 195 974 480
 338  86 142 382 768 405 165 899  60 157 141 610 391 400 442 663  30 127
 554 867 709 593 235 434 588 515 568 335 535 844  14 470 983 518 915 852
 895 301 815 422 768 115 399 555 854 198  91 675 654 117 521 218 295 408
 907 380  95 853 982 197 403 110 476  33]
Max value: 992 Min value: 14 Mean value: 490.69


### Topic 2 :Array Indexing, Slicing, & Reshaping
Task 1: Create a NumPy array of shape (6,6) filled with random integers. Extract:
- The second row
- The last two columns
- The diagonal elements

In [65]:
np.random.seed(1)
arr5 = np.random.randint(1, 40, size=(6, 6))
print(arr5)
second_row = arr5[1]
print('Second Row\n',second_row )
last_two_cols = arr5[:, 4:]
print('Last Two Columns\n', last_two_cols)
diagonal_eles = np.diagonal(arr5)
print('Diagonal elements:\n', diagonal_eles)

[[38 13  9 10 12  6]
 [16  1 17  2 13  8]
 [ 7 26 21 38 19 21]
 [12 29 30 15  5 24]
 [24 31 33 23 14 10]
 [ 8 23  2  1 18  9]]
Second Row
 [16  1 17  2 13  8]
Last Two Columns
 [[12  6]
 [13  8]
 [19 21]
 [ 5 24]
 [14 10]
 [18  9]]
Diagonal elements:
 [38  1 21 15 14  9]



Task 2: Given a 1D array of numbers from 1 to 50, reshape it into a 5×10 matrix
and extract the first three rows.

In [78]:
arr6 = np.arange(1,51).reshape(5, 10)
first_three_rows = arr6[:3]
print(f'First three rows:\n {first_three_rows}')

First three rows:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


Task 3:. Create a 3D array of shape (4,4,4). Extract a sub-array containing
elements from the second and third layers in first dimension (dim=0).

In [ ]:
np.random.seed(1)
arr7 = np.random.randint(1, 100, size=(4, 4, 4))
sub_array = arr7[1:3]
print(f'Second and third layers:\n {sub_array}')

Second and third layers:
 [[[19 85 12 29]
  [30 15 51 69]
  [88 88 95 97]
  [87 14 10  8]]

 [[64 62 23 58]
  [ 2  1 61 82]
  [ 9 89 14 48]
  [73 31 72  4]]]



Task 4:. Write a function that takes a NumPy array and reverses its elements
without using loops.

In [ ]:
def reverseArr(np_arr):
    reversed_arr = np_arr[::-1]
    return reversed_arr

np_arr = np.arange((5))
reverseArr(np_arr)

array([4, 3, 2, 1, 0])

Task 5:. Generate a 2D NumPy array of random integers and swap the first and
last rows using array slicing.

In [128]:
np.random.seed(1)
np_random_arr = np.random.randint(1, 20, size=(3, 4))
swap_rows = np_random_arr[::-1]
print(f'Random Array:\n{np_random_arr}')
print(f'Swapped Rows:\n{swap_rows}')

Random Array:
[[ 6 12 13  9]
 [10 12  6 16]
 [ 1 17  2 13]]
Swapped Rows:
[[ 1 17  2 13]
 [10 12  6 16]
 [ 6 12 13  9]]


Task 6:. Create a NumPy array of shape (3, 6) and reshape it into a 2×9 matrix.
Explain how reshaping affects memory allocation.

In [ ]:
np_arr2 = np.arange(18).reshape(3, 6)
reshaped_arr = np_arr2.reshape(2, 9)
print(f'Original Array (3, 6):\n {np_arr2} \n',
      f'Reshaped Array (2, 9):\n {reshaped_arr}')
# Reshaping does not create new memory and just changes how the data is viewed 
# The data remains in the same place in memory but the rows and columns(shape)changes.
# So reshaping only alters the structure and not the actual data

Original Array (3, 6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 
 Reshaped Array (2, 9):
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


Task 7:. Given a NumPy array `arr = np.array([[5,10,15], [20,25,30], [35,40,45]])`,
extract all elements greater than 20 using boolean indexing.

In [139]:
arr8 = np.array([[5,10,15], [20,25,30], [35,40,45]])
condition = arr8 > 20
new_arr = arr8[condition]
print(f'Elements greater than 20: {new_arr}')

Elements greater than 20: [25 30 35 40 45]




Task 8:. Create a function that takes a 2D array and returns its transposed
version.


In [146]:
def transposeArr(arr9):
    transposed_arr = np.transpose(arr9)
    print(f'Original Array:\n {arr9} \n')
    print(f'Transposed Array:\n {transposed_arr}')
    return

arr9 = np.arange(12).reshape(3, 4)
transposeArr(arr9)


Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Topic 3 :Broadcasting & Vectorized Operations
Task 1: Create two NumPy arrays of shape (3,3) and add them using
broadcasting without using loops.

In [151]:
a1 = np.random.randint(1, 20, size=(3, 3))
a2 = np.random.randint(3, 18, size=(3, 3))
print(f'First Array:\n{a1}\n', f'Second Array:\n{a2}')
sum_arr = a1 + a2
print(f'Sum of two arrays:\n{sum_arr}')

First Array:
[[15  1  2]
 [18 14  4]
 [ 1 14  7]]
 Second Array:
[[ 7  8  9]
 [ 5 15 14]
 [ 8 14 10]]
Sum of two arrays:
[[22  9 11]
 [23 29 18]
 [ 9 28 17]]


Task 2. Given a NumPy array, multiply each row by a different scalar using
broadcasting.

In [166]:
np.random.seed(1)
a3 = np.random.randint(1, 15, size=(3, 3))
multiply_arr = a3 *  np.array([3, 4, 5])[:, None] # converts the 1D array [3, 4, 5] into a column vector (shape (3, 1))
print(f'Original Array:\n{a3}\n',
      f'Multiplied Array:\n{multiply_arr}')

Original Array:
[[ 6 12 13]
 [ 9 10 12]
 [ 6  1  1]]
 Multiplied Array:
[[18 36 39]
 [36 40 48]
 [30  5  5]]



Task 3. Create a 3×3 matrix and add a 1D array of size 3 to it using broadcasting.

In [171]:
arr_mat = np.arange(9).reshape(3, 3)
print(f'3x3 matrix: \n{arr_mat}')
arr_1d = np.arange(1,4)
print(f'Size 3 array: \n{arr_1d}')
add_arr = arr_mat + arr_1d
print(f'Addition: \n{add_arr}')

3x3 matrix: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Size 3 array: 
[1 2 3]
Addition: 
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]



Task 4. Implement a function that performs element-wise multiplication between
two numpy arrays of different shapes using broadcasting.

In [177]:
def multiplyArr(arr_shape1, arr_shape2):
    multiply_arr = arr_shape1 * arr_shape2
    print(f'First Array:\n{arr_shape1}\n',
          f'Second Array:\n{arr_shape2}')
    print(f'Multiplication:\n {multiply_arr}')
    return 

arr_shape1 = np.arange(12).reshape(4, 3)
arr_shape2 = np.arange(1, 4)
multiplyArr(arr_shape1, arr_shape2)

First Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 Second Array:
[1 2 3]
Multiplication:
 [[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]
 [ 9 20 33]]



Task 5. Write a Python program to compute the dot product of two matrices
using NumPy.

In [179]:
dot_prod = np.dot(arr_shape1, arr_shape2)
dot_prod

array([ 8, 26, 44, 62])

Task 6. Create a NumPy array of shape (5,5) and replace all elements greater
than a given threshold with their squared values using vectorized operations.




Task 7. Generate two random 2D arrays of different shapes and use
broadcasting to compute their element-wise sum.
Task 8. Demonstrate the use of broadcasting to compute the mean of each
column in a matrix without using loops.
Task 9. Write a function that computes the cosine similarity between two NumPy
vectors using broadcasting and vectorized operations.
 