### Topic 1 : Creating Arrays
Task 1: Write a Python program to create a NumPy array of integers from 1 to
20 and reshape it into a 4×5 matrix.

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 21).reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Task 2. Create a NumPy array of shape (5,5) filled with random float values
between 0 and 1.

In [3]:
arr2 = np.random.rand(5, 5)
arr2

array([[0.49990179, 0.0956204 , 0.23929055, 0.27939241, 0.62721275],
       [0.29607415, 0.87813095, 0.6416259 , 0.96605135, 0.09748149],
       [0.77676525, 0.25243007, 0.72313249, 0.03787486, 0.12217841],
       [0.41569133, 0.84944411, 0.052843  , 0.82649308, 0.17287253],
       [0.09967515, 0.69835762, 0.58972561, 0.75188267, 0.41745572]])

Task 3. Write a function that takes a list as input and converts it into a NumPy
array. Ensure the function can handle lists of different lengths and nested lists.

In [4]:
def convert_list(list_input):
    list_arr = np.array(list_input, dtype=list)
    return list_arr

user_input = input("Enter a list of numbers:")
user_input = user_input.replace("][", "], [")
user_list = eval(user_input)
convert_list(user_list)

array([1, 2], dtype=object)

Task 4. Create an identity matrix of size 6×6 using NumPy.

In [5]:
identity_matrix = np.eye(6, 6)
identity_matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Task 5. Generate an array of 10 evenly spaced values between -5 and 5 using
`linspace`. Explain the difference between `linspace` and `arange`.


In [6]:
even_spaced_arr = np.linspace(0, 5, 10)
even_spaced_arr
# linspace is used to evenly divide the range from start to stop into a specific number of values, 
# while arange is used when you want numbers with a specific step between them.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Task 6. Create a 3D NumPy array of shape (3,3,3) filled with random integers
between 10 and 50.

In [7]:
random_arr3 = np.random.random_integers(10, 50, (3, 3, 3))
random_arr3

C:\Users\acer\AppData\Local\Temp\ipykernel_15576\1200005687.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 50 + 1) instead
  random_arr3 = np.random.random_integers(10, 50, (3, 3, 3))


array([[[21, 37, 39],
        [29, 10, 25],
        [40, 11, 11]],

       [[10, 46, 30],
        [21, 34, 22],
        [15, 11, 15]],

       [[42, 35, 28],
        [34, 28, 23],
        [45, 47, 26]]], dtype=int32)


Task 7. Write a Python program to generate an array of zeros and ones of shape
(4,4).

In [8]:
zeros_arr = np.zeros((4, 4), dtype = np.int32)
ones_arr = np.ones((4, 4), dtype = np.int32)
zeros_arr, ones_arr

(array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=int32),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=int32))

Task 8. Generate a NumPy array of 100 random integers between 1 and 1000.
Find the maximum, minimum, and mean values in the array.


In [9]:
arr4 = np.random.randint(1, 1000, 100)
max_val = np.max(arr4)
min_val = np.min(arr4)
mean_val = np.mean(arr4)

print(f'Array Values: {arr4}')
print(f'Max value: {max_val}',
    f'Min value: {min_val}',
    f'Mean value: {mean_val}')

Array Values: [476 499 995 211 943 470 306 508 422 918 489 828 841 191 678 332 350 974
 577  16 613 149 989 762 763 883 529 407 905 203 578 926 287 447 881 441
 134  40 464 737 690 279  76 236 549 770 397 844 489 534 531 110  55 961
 491 289 524 517 890 329 865 263 227 588 477 777 645 348 411 989 900 321
 183 575 530 372 164 767   1 998 829 461 629  78 374 757 782 546 425 894
  63 770  30 493 408 808  63 777 407 459]
Max value: 998 Min value: 1 Mean value: 521.77


### Topic 2 :Array Indexing, Slicing, & Reshaping
Task 1: Create a NumPy array of shape (6,6) filled with random integers. Extract:
- The second row
- The last two columns
- The diagonal elements

In [10]:
np.random.seed(1)
arr5 = np.random.randint(1, 40, size=(6, 6))
print(arr5)
second_row = arr5[1]
print('Second Row\n',second_row )
last_two_cols = arr5[:, 4:]
print('Last Two Columns\n', last_two_cols)
diagonal_eles = np.diagonal(arr5)
print('Diagonal elements:\n', diagonal_eles)

[[38 13  9 10 12  6]
 [16  1 17  2 13  8]
 [ 7 26 21 38 19 21]
 [12 29 30 15  5 24]
 [24 31 33 23 14 10]
 [ 8 23  2  1 18  9]]
Second Row
 [16  1 17  2 13  8]
Last Two Columns
 [[12  6]
 [13  8]
 [19 21]
 [ 5 24]
 [14 10]
 [18  9]]
Diagonal elements:
 [38  1 21 15 14  9]



Task 2: Given a 1D array of numbers from 1 to 50, reshape it into a 5×10 matrix
and extract the first three rows.

In [11]:
arr6 = np.arange(1,51).reshape(5, 10)
first_three_rows = arr6[:3]
print(f'First three rows:\n {first_three_rows}')

First three rows:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


Task 3:. Create a 3D array of shape (4,4,4). Extract a sub-array containing
elements from the second and third layers in first dimension (dim=0).

In [12]:
np.random.seed(1)
arr7 = np.random.randint(1, 100, size=(4, 4, 4))
sub_array = arr7[1:3]
print(f'Second and third layers:\n {sub_array}')

Second and third layers:
 [[[19 85 12 29]
  [30 15 51 69]
  [88 88 95 97]
  [87 14 10  8]]

 [[64 62 23 58]
  [ 2  1 61 82]
  [ 9 89 14 48]
  [73 31 72  4]]]



Task 4:. Write a function that takes a NumPy array and reverses its elements
without using loops.

In [13]:
def reverseArr(np_arr):
    reversed_arr = np_arr[::-1]
    return reversed_arr

np_arr = np.arange((5))
reverseArr(np_arr)

array([4, 3, 2, 1, 0])

Task 5:. Generate a 2D NumPy array of random integers and swap the first and
last rows using array slicing.

In [14]:
np.random.seed(1)
np_random_arr = np.random.randint(1, 20, size=(3, 4))
swap_rows = np_random_arr[::-1]
print(f'Random Array:\n{np_random_arr}')
print(f'Swapped Rows:\n{swap_rows}')

Random Array:
[[ 6 12 13  9]
 [10 12  6 16]
 [ 1 17  2 13]]
Swapped Rows:
[[ 1 17  2 13]
 [10 12  6 16]
 [ 6 12 13  9]]


Task 6:. Create a NumPy array of shape (3, 6) and reshape it into a 2×9 matrix.
Explain how reshaping affects memory allocation.

In [15]:
np_arr2 = np.arange(18).reshape(3, 6)
reshaped_arr = np_arr2.reshape(2, 9)
print(f'Original Array (3, 6):\n {np_arr2} \n',
      f'Reshaped Array (2, 9):\n {reshaped_arr}')
# Reshaping does not create new memory and just changes how the data is viewed 
# The data remains in the same place in memory but the rows and columns(shape)changes.
# So reshaping only alters the structure and not the actual data

Original Array (3, 6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 
 Reshaped Array (2, 9):
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


Task 7:. Given a NumPy array `arr = np.array([[5,10,15], [20,25,30], [35,40,45]])`,
extract all elements greater than 20 using boolean indexing.

In [16]:
arr8 = np.array([[5,10,15], [20,25,30], [35,40,45]])
condition = arr8 > 20
new_arr = arr8[condition]
print(f'Elements greater than 20: {new_arr}')

Elements greater than 20: [25 30 35 40 45]




Task 8:. Create a function that takes a 2D array and returns its transposed
version.


In [17]:
def transposeArr(arr9):
    transposed_arr = np.transpose(arr9)
    print(f'Original Array:\n {arr9} \n')
    print(f'Transposed Array:\n {transposed_arr}')
    return

arr9 = np.arange(12).reshape(3, 4)
transposeArr(arr9)


Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Topic 3 :Broadcasting & Vectorized Operations
Task 1: Create two NumPy arrays of shape (3,3) and add them using
broadcasting without using loops.

In [18]:
a1 = np.random.randint(1, 20, size=(3, 3))
a2 = np.random.randint(3, 18, size=(3, 3))
print(f'First Array:\n{a1}\n', f'Second Array:\n{a2}')
sum_arr = a1 + a2
print(f'Sum of two arrays:\n{sum_arr}')

First Array:
[[ 8 14  7]
 [19  6 19]
 [12 11 15]]
 Second Array:
[[ 5  7 10]
 [10 12  4]
 [10 17  3]]
Sum of two arrays:
[[13 21 17]
 [29 18 23]
 [22 28 18]]


Task 2. Given a NumPy array, multiply each row by a different scalar using
broadcasting.

In [19]:
np.random.seed(1)
a3 = np.random.randint(1, 15, size=(3, 3))
multiply_arr = a3 *  np.array([3, 4, 5])[:, None] # converts the 1D array [3, 4, 5] into a column vector (shape (3, 1))
print(f'Original Array:\n{a3}\n',
      f'Multiplied Array:\n{multiply_arr}')

Original Array:
[[ 6 12 13]
 [ 9 10 12]
 [ 6  1  1]]
 Multiplied Array:
[[18 36 39]
 [36 40 48]
 [30  5  5]]



Task 3. Create a 3×3 matrix and add a 1D array of size 3 to it using broadcasting.

In [20]:
arr_mat = np.arange(9).reshape(3, 3)
print(f'3x3 matrix: \n{arr_mat}')
arr_1d = np.arange(1,4)
print(f'Size 3 array: \n{arr_1d}')
add_arr = arr_mat + arr_1d
print(f'Addition: \n{add_arr}')

3x3 matrix: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Size 3 array: 
[1 2 3]
Addition: 
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]



Task 4. Implement a function that performs element-wise multiplication between
two numpy arrays of different shapes using broadcasting.

In [21]:
def multiplyArr(arr_shape1, arr_shape2):
    multiply_arr = arr_shape1 * arr_shape2
    print(f'First Array:\n{arr_shape1}\n',
          f'Second Array:\n{arr_shape2}')
    print(f'Multiplication:\n {multiply_arr}')
    return 

arr_shape1 = np.arange(12).reshape(4, 3)
arr_shape2 = np.arange(1, 4)
multiplyArr(arr_shape1, arr_shape2)

First Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 Second Array:
[1 2 3]
Multiplication:
 [[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]
 [ 9 20 33]]



Task 5. Write a Python program to compute the dot product of two matrices
using NumPy.

In [22]:
dot_prod = np.dot(arr_shape1, arr_shape2)
dot_prod

array([ 8, 26, 44, 62])

Task 6. Create a NumPy array of shape (5,5) and replace all elements greater
than a given threshold with their squared values using vectorized operations.

In [23]:
a4 = np.arange(25).reshape(5, 5)
number = 12
def squaredArr(x: int, n: int):
    # squared_val = np.where(x > n, x**2, x) # boolean indexing
    if x > n:
        squared_val = x**2
    else:
        squared_val = x
    return squared_val

squared_vec = np.vectorize(squaredArr)
squared_vec(a4, number)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

Task 7. Generate two random 2D arrays of different shapes and use
broadcasting to compute their element-wise sum.

In [24]:
np.random.seed(0)
ra1 = np.random.randint(1, 20, size=(2, 4))
ra2 = np.random.randint(3, 15, size=(2, 1))
print(f'First Random Array:\n{ra1}\n',
      f'Second Random Array:\n{ra2}')
sum_result = ra1 + ra2
sum_result

First Random Array:
[[13 16  1  4]
 [ 4  8 10 19]]
 Second Random Array:
[[ 7]
 [10]]


array([[20, 23,  8, 11],
       [14, 18, 20, 29]], dtype=int32)

Task 8. Demonstrate the use of broadcasting to compute the mean of each
column in a matrix without using loops.

In [25]:
np.random.seed(1)
mat_arr = np.random.randint(2, 50, size=(7, 5))
print(f'Random Matrix:\n{mat_arr}') 
col_mean = np.mean(mat_arr, axis=0)
print(f'Column Mean:\n{col_mean}')


Random Matrix:
[[39 45 14 10 11]
 [13  7 17  2 18]
 [ 3 14  9 47  8]
 [27 22 39 20 22]
 [13 44 30 31 16]
 [ 6 25 25 43 32]
 [34 24 15 43 11]]
Column Mean:
[19.28571429 25.85714286 21.28571429 28.         16.85714286]



Task 9. Write a function that computes the cosine similarity between two NumPy
vectors using broadcasting and vectorized operations.
 

In [26]:
def cosSimilarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm1 = np.sqrt(np.sum(vec1 ** 2))  
    norm2 = np.sqrt(np.sum(vec2 ** 2))
    cosineSim = dot_product / (norm1 * norm2) 
    return cosineSim

vec1 = np.arange(5)
vec2 = np.arange(7, 12) 
cosSimilarity(vec1, vec2)

np.float64(0.8962214298964417)

### Topic 4 :Mathematical & Statistical Operations in NumPy
Task 1.Create a NumPy array and compute its mean, median, standard deviation,
and variance.

In [27]:
np.random.seed(1)
ra5 = np.random.random(10)
arr_mean = np.mean(ra5)
arr_median = np.median(ra5)
arr_std = np.std(ra5)
arr_var = np.var(ra5)
print(f'Random Array:\n{ra5}')
print(f'Mean: {arr_mean}\n', 
      f'Median: {arr_median}\n',
      f'Standard Deviation: {arr_std}\n',
      f'Variance: {arr_var}')

Random Array:
[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]
Mean: 0.3146293077834573
 Median: 0.32394664983744376
 Standard Deviation: 0.20644137281355943
 Variance: 0.04261804040914704


Task 2. Write a function that normalizes a given NumPy array using mean and
standard deviation.

In [28]:
def normalizedArr(arr):
    arr_mean = np.mean(arr)
    arr_std = np.std(arr)
    normalized_arr = (arr - arr_mean) / arr_std
    return normalized_arr
ra6 = np.arange(1, 20, 2)
normalizedArr(ra6)
print(f'Original Array:\n{ra6}')
print(f'Normalized Array:\n{normalizedArr(ra6)}')

Original Array:
[ 1  3  5  7  9 11 13 15 17 19]
Normalized Array:
[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


Task 3. Generate a 4×4 matrix and compute the sum of each row and column
separately.

In [29]:
np.random.seed(1)
random_arr4 = np.random.randint(1, 20, size=(4, 4))
print(f'Random Array:\n{random_arr4}')
col_sum = np.sum(random_arr4, axis = 0)
row_sum = np.sum(random_arr4, axis = 1)
print(f'Column Sum:\n{col_sum}')
print(f'Row Sum:\n{row_sum}')

Random Array:
[[ 6 12 13  9]
 [10 12  6 16]
 [ 1 17  2 13]
 [ 8 14  7 19]]
Column Sum:
[25 55 28 57]
Row Sum:
[40 44 33 48]


Task 4. Compute the cumulative sum and cumulative product of a given NumPy
array.

In [30]:
c_arr = np.array([2, 4, 7, 3, 5, 1])
print(f'Original Array:\n{c_arr}')
c_sum = np.cumsum(c_arr)
print(f'Cumulative Sum:\n{c_sum}')
c_prod = np.cumprod(c_arr)
print(f'Cumulative Product:\n{c_prod}')

Original Array:
[2 4 7 3 5 1]
Cumulative Sum:
[ 2  6 13 16 21 22]
Cumulative Product:
[  2   8  56 168 840 840]


Task 5. Given a 2D array, find the 2d index of the maximum and minimum
element in the entire array.

In [31]:
np.random.seed(1)
arr_2d = np.random.randint(1, 25, size=(3, 3))
print(f'2D Array:\n{arr_2d}')
max_val = np.unravel_index(np.argmax(arr_2d), arr_2d.shape)
min_val = np.unravel_index(np.argmin(arr_2d), arr_2d.shape)
print(f'Max Value Index:\n{max_val}\n', 
      f'Min Value Index:\n{min_val}')

2D Array:
[[ 6 12 13]
 [ 9 10 12]
 [ 6 16  1]]
Max Value Index:
(np.int64(2), np.int64(1))
 Min Value Index:
(np.int64(2), np.int64(2))


Task 6. Write a Python program that standardizes a dataset (scales values to
have a mean of 0 and standard deviation of 1).

In [32]:
np.random.seed(1)
data = np.random.randint(1, 25, size=(3, 2))
data_mean = np.mean(data, axis=0)
data_std = np.std(data, axis=0)
standardized = (data - data_mean) / data_std
print(f'Original Data:\n{data}\n', 
      f'Mean:\n{data_mean}\n', 
      f'Standard Deviation:\n{data_std}\n', 
      f'Standardized Data:\n{standardized}')


Original Data:
[[ 6 12]
 [13  9]
 [10 12]]
 Mean:
[ 9.66666667 11.        ]
 Standard Deviation:
[2.86744176 1.41421356]
 Standardized Data:
[[-1.27872403  0.70710678]
 [ 1.16247639 -1.41421356]
 [ 0.11624764  0.70710678]]


Task 7. Generate a NumPy array of 1000 random values following a normal
distribution.

In [33]:
norm_dist = np.random.normal(50, 10, 1000) # mean=50, std=10, size=1000
print(f'Normal Distribution:\n{norm_dist}')

Normal Distribution:
[33.98278996 35.22170429 54.83495847 51.88436605 45.35313677 58.61827117
 23.4573802  61.52264916 51.96643411 34.5478585  49.11895915 58.52239322
 56.77234006 48.93121574 57.25274065 59.34889154 61.18296977 50.5561319
 53.76656635 53.76135021 48.35809229 49.15456552 59.31558162 67.06934969
 41.08086241 67.35596532 43.68891669 40.92656644 53.74751973 45.26617246
 45.45479176 49.14661937 65.03188379 61.60641123 45.17058603 31.9337099
 40.84552392 49.30266015 41.50045228 50.50623231 57.05072381 33.20058045
 69.99975637 61.56963274 51.93117963 34.46992592 49.89986462 56.49165533
 65.58572932 52.38351806 51.08086617 60.15262919 59.59636776 48.72696852
 56.98554164 27.74504915 37.3177065  63.92182014 69.23831905 59.91091266
 53.80610804 42.52233641 36.82322497 63.32910075 43.1545975  62.55982326
 54.96726354 53.29275803 49.98810092 46.92707375 48.16463001 44.47024849
 48.44287196 55.72392274 57.59955476 57.35681993 60.13892432 42.61568819
 52.57706672 38.62548272 65.7814

Task 8. Create a function that calculates the correlation coefficient between two
NumPy arrays.

In [34]:
np.random.seed(1)
corr_arr1 = np.random.randint(1, 15, size=(3, 2))
corr_arr2 = np.random.randint(12, 20, size=(3, 2))
def coefficientCorr(arr1, arr2):
    corr_coeff = np.corrcoef(arr1, arr2, rowvar=False)
    return corr_coeff

result = coefficientCorr(corr_arr1, corr_arr2)
print(result)

[[ 1.         -0.82199494 -0.9686196  -0.98648649]
 [-0.82199494  1.          0.65465367  0.90419443]
 [-0.9686196   0.65465367  1.          0.9148074 ]
 [-0.98648649  0.90419443  0.9148074   1.        ]]


### Topic 5 :Working with Missing Data in NumPy
Task 1. Create a NumPy array with some missing values (`np.nan`). Write a
function that identifies the indices of missing values.

In [ ]:
single_arr = np.array([2, 4, 7, 12, np.nan, 23, 6])

def findNanIndex(arr):
    nan_indices = np.where(np.isnan(arr))
    return nan_indices

findNanIndex(single_arr)

(array([4]),)


Task 1. Given an array with missing values, replace all `np.nan` values with the
mean of the non-missing values.

In [40]:
arr_nan = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])
mean_nan = np.nanmean(arr_nan)
arr_nan_value = np.where(np.isnan(arr_nan), mean_nan, arr_nan)
print(f'Array with NaN values:\n{arr_nan}\n',
      f'Mean of NaN values:\n{mean_nan}\n',
      f'Array with NaN replaced by mean:\n{arr_nan_value}') 

Array with NaN values:
[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
 Mean of NaN values:
5.285714285714286
 Array with NaN replaced by mean:
[[1.         2.         5.28571429]
 [4.         5.28571429 6.        ]
 [7.         8.         9.        ]]



Task 2. Implement a function that removes all rows containing `np.nan` from a
given 2D NumPy array.

In [49]:
np.random.seed(0)
random_array = np.random.randint(1, 10, size=(5, 4)).astype(float)
random_array[1, 2] = np.nan
random_array[3, 0] = np.nan
random_array[4, 3] = np.nan

print(random_array)
def removeNanRows(arr_row):
    arr_row = arr_row[~np.isnan(arr_row).any(axis=1)]
    return arr_row
removed_rows = removeNanRows(random_array)
print(f'Array with NaN rows removed:\n{removed_rows}')

[[ 6.  1.  4.  4.]
 [ 8.  4. nan  3.]
 [ 5.  8.  7.  9.]
 [nan  2.  7.  8.]
 [ 8.  9.  2. nan]]
Array with NaN rows removed:
[[6. 1. 4. 4.]
 [5. 8. 7. 9.]]


Task 3. Write a Python program that fills missing values in an array using linear
interpolation.



Task 4. Given a dataset with missing values, replace them using forward-fill and
backward-fill techniques.
Task 5. Create a 5×5 matrix with some missing values and compute the mean
while ignoring `np.nan`.
Task 6. Write a function that detects outliers in a NumPy array using the
Interquartile Range (IQR) method.
Task 7. Generate an array with missing values and replace them with the median
of the column.
